blank_issues_enabled: false
contact_links:
  - name: Avensio Async-Pool Discussions
    url: https://github.com/AvensioDev/async-pool/discussions
    about: Ask and answer questions with the community.
